[workspace]
resolver = "2"
members = ["core", "python"]

[workspace.package]
version = "0.1.8"
edition = "2021"
license = "MIT"
repository = "https://github.com/kevinhu/plsfix"

[workspace.dependencies]
plsfix = { path = "core" }
encoding = "0.2.33"
encoding_rs = "0.8.35"
fancy-regex = "0.14.0"
htmlize = { version = "1.1.0", default-features = false }
icu = "1.5.0"
lazy_static = "1.5.0"
oem_cp = "2.0.0"
phf = "0.11"
phf_codegen = "0.11"
pretty_assertions = "0.4.1"
pyo3 = "0.28.3"
regex = "1.11.1"
rustc-hash = "2.1.0"
serde = "1.0"
serde_json = "1.0"
unicode-normalization = { version = "0.1.24", default-features = false }

[profile.release]
debug = true
