//! Compile-time tables generated by `build.rs`, all re-exported through
//! `chardata`.
//!
//! `UPPER_ALIASES` maps ftfy-specific ALL-CAPS HTML named-entity aliases
//! (`&EACUTE;` → `É`) that aren't in the WHATWG named-character-reference set
//! to their decoded value. It's a `phf::Map` — zero runtime init, no allocations.
//!
//! `UTF8_CONTINUATION_STRICT_SET` reconstructs the char class from the
//! `(?<![strict])` lookbehind dropped from `UTF8_DETECTOR_RE` — the `regex`
//! crate doesn't support lookarounds, so `decode_inconsistent_utf8` checks
//! the preceding char against this set instead. It's generated from the
//! named-character list in `STRICT_NAMES`.
//!
//! `lookup_width` folds fullwidth/halfwidth characters to their NFKC standard
//! form for `fix_character_width`.

include!(concat!(env!("OUT_DIR"), "/chardata_generated.rs"));
