//! ftfy-specific ALL-CAPS HTML named-entity aliases (`&EACUTE;` → `É`)
//! that aren't in the WHATWG named-character-reference set.
//!
//! Everything here is generated by `build.rs` and expands to a
//! `hashify::tiny_map!` perfect-hash `match` — zero runtime init, no
//! allocations.

include!(concat!(env!("OUT_DIR"), "/html_entities.rs"));
