//! ftfy-specific ALL-CAPS HTML named-entity aliases (`&EACUTE;` → `É`)
//! that aren't in the WHATWG named-character-reference set.
//!
//! Everything here is generated by `build.rs` as a `phf::Map` — zero
//! runtime init, no allocations.

include!(concat!(env!("OUT_DIR"), "/html_entities.rs"));
