//! Compile-time table for the UTF-8-mojibake detector.
//!
//! `UTF8_CONTINUATION_STRICT_SET` reconstructs the char class from the
//! `(?<![strict])` lookbehind dropped from `UTF8_DETECTOR_RE` — the `regex`
//! crate doesn't support lookarounds, so `decode_inconsistent_utf8` checks
//! the preceding char against this set instead. Generated by `build.rs`
//! from the named-character list in `STRICT_NAMES`.

include!(concat!(env!("OUT_DIR"), "/utf8.rs"));
