//! Generate `lookup_upper_alias` — a `hashify::tiny_map!` perfect-hash for
//! ftfy's ALL-CAPS HTML entity aliases (`&EACUTE;` → `É`). The same
//! derivation used to happen at runtime via `lazy_static! { FxHashMap }`
//! (~500 µs one-shot); doing it at compile time eliminates that init cost.
//!
//! `htmlize` is pulled in as a build-dependency (`entities` feature only)
//! so we can iterate `htmlize::ENTITIES` directly — the WHATWG table stays
//! single-sourced from upstream, no vendored copy.

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_path = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("html_entities.rs");
    let mut out = BufWriter::new(File::create(&out_path).unwrap());

    let mut entries: Vec<(String, String)> = Vec::new();
    for (name_bytes, val_bytes) in htmlize::ENTITIES.entries() {
        let name = match std::str::from_utf8(name_bytes) {
            Ok(s) => s,
            Err(_) => continue,
        };
        if !name.ends_with(';') {
            continue;
        }
        let bare = &name[1..name.len() - 1];
        if !bare.chars().all(|c| !c.is_alphabetic() || c.is_lowercase()) {
            continue;
        }
        let upper_key = format!("&{};", bare.to_uppercase());
        if htmlize::ENTITIES.contains_key(upper_key.as_bytes()) {
            continue;
        }
        let val = match std::str::from_utf8(val_bytes) {
            Ok(s) => s,
            Err(_) => continue,
        };
        entries.push((upper_key, val.to_uppercase()));
    }

    writeln!(
        out,
        "/// Look up an ftfy ALL-CAPS HTML entity alias. Returns the decoded\n\
         /// value or `None`. Generated by `build.rs` from `htmlize::ENTITIES`."
    )
    .unwrap();
    writeln!(
        out,
        "pub fn lookup_upper_alias(key: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(out, "    hashify::tiny_map! {{").unwrap();
    writeln!(out, "        key.as_bytes(),").unwrap();
    for (key, val) in &entries {
        writeln!(
            out,
            "        {} => {},",
            rust_string_literal(key),
            rust_string_literal(val),
        )
        .unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

/// Format a string as a Rust `"…"` literal with `\u{…}` escapes for any
/// non-ASCII codepoint, so the generated source is plain ASCII.
fn rust_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c if (c as u32) < 0x20 || c == '\u{7f}' => {
                out.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c if (c as u32) < 0x80 => out.push(c),
            c => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
        }
    }
    out.push('"');
    out
}
