[package]
name = "plsfix"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Text cleaner upper"
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = { workspace = true }
encoding_rs = { workspace = true }
fancy-regex = { workspace = true }
htmlize = { workspace = true, features = ["unescape"] }
icu = { workspace = true }
lazy_static = { workspace = true }
oem_cp = { workspace = true, features = ["alloc"] }
regex = { workspace = true }
rustc-hash = { workspace = true }
unicode-normalization = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
unicode_names2 = { workspace = true }
